package com.devmind.decisionlab;

import com.devmind.decisionlab.dataset.model.DecisionDatasetEntity;
import com.devmind.decisionlab.dataset.model.DecisionDatasetItemEntity;
import org.hibernate.boot.Metadata;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.dialect.H2Dialect;
import org.hibernate.dialect.MySQLDialect;
import org.hibernate.dialect.PostgreSQLDialect;
import org.hibernate.tool.schema.internal.SchemaCreatorImpl;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * CAP-56 建表口径的跨库回归网（照 {@code devmind-common} 的 {@code LobColumnTypeTest} 的先例，
 * 只用 Hibernate 元数据导出 DDL，不起 Spring 上下文）。
 *
 * <p>为什么这几条必须钉住——它们全都是<b>只在某个库上才炸</b>的错误，本地 H2 跑得欢不代表线上能起：
 * <ul>
 *   <li>裸 {@code @Lob}：PG 落成 oid 大对象（auto-commit 读直接抛错），MySQL 落成 tinytext；</li>
 *   <li>{@code version} 当列名：H2 保留字，建表就失败（本模块用的是 {@code dataset_version}）；</li>
 *   <li>Boolean 列带 {@code @ColumnDefault}：MySQL 的 bit 列建不出来（项目已两次事故）。</li>
 * </ul>
 * 三个方言各导一遍：H2 是本地与 E2E 的库，PG 是 140.156/143/224 的库，MySQL 是历史共享库。</p>
 */
class DecisionLabSchemaTest {

    private String exportDdl(Class<?> dialect) {
        var registry = new StandardServiceRegistryBuilder()
                .applySetting("hibernate.dialect", dialect.getName())
                .build();
        Metadata metadata = new MetadataSources(registry)
                .addAnnotatedClass(DecisionDatasetEntity.class)
                .addAnnotatedClass(DecisionDatasetItemEntity.class)
                .buildMetadata();
        String ddl = String.join("\n", new SchemaCreatorImpl(registry)
                .generateCreationCommands(metadata, false)).toLowerCase();
        StandardServiceRegistryBuilder.destroy(registry);
        return ddl;
    }

    /**
     * 取该列的 DDL 片段（从列名到下一个逗号）。
     *
     * <p>不能按行切：{@code SchemaCreatorImpl} 把整条 CREATE TABLE 输出成一行，
     * 按行取会拿到整张表——于是"id 列的 {@code generated by default as identity}"会被误判成
     * frozen 列有 default（第一版就是这么红的）。按列名到逗号切片才谈得上"看这一列"。</p>
     */
    private static String columnDef(String ddl, String column) {
        int start = ddl.indexOf(" " + column + " ");
        if (start < 0) {
            return "";
        }
        int end = ddl.indexOf(',', start);
        return end < 0 ? ddl.substring(start) : ddl.substring(start, end);
    }

    @Test
    void pgLobColumnsAreInlineTextNotOid() {
        String ddl = exportDdl(PostgreSQLDialect.class);
        for (String column : new String[] {"state_json", "questions_json", "gold_json", "freeze_manifest"}) {
            assertTrue(columnDef(ddl, column).contains(" text"),
                    "PG 上 " + column + " 应为 text（@Lob 必须配 @JdbcTypeCode(LONGVARCHAR)）");
        }
        assertFalse(ddl.contains(" oid "), "PG 不应出现 oid 大对象列——那会让读写炸在 auto-commit 上");
    }

    @Test
    void mysqlLobColumnsAreLongtext() {
        String ddl = exportDdl(MySQLDialect.class);
        for (String column : new String[] {"state_json", "questions_json", "gold_json", "freeze_manifest"}) {
            assertTrue(columnDef(ddl, column).contains("longtext"),
                    "MySQL 上 " + column + " 应为 longtext（依赖 @Column(length = 16_777_216)）");
        }
    }

    @Test
    void versionColumnIsRenamedSoH2CanCreateTheTable() {
        for (Class<?> dialect : new Class<?>[] {H2Dialect.class, PostgreSQLDialect.class, MySQLDialect.class}) {
            String ddl = exportDdl(dialect);
            assertTrue(columnDef(ddl, "dataset_version").contains("dataset_version"),
                    dialect.getSimpleName() + " 上评测集版本列应为 dataset_version（version 是 H2 保留字）");
            assertFalse(ddl.contains(" version "),
                    dialect.getSimpleName() + " 上不该有裸 version 列——建表会直接失败");
        }
    }

    @Test
    void booleanColumnsCarryNoDefaultClause() {
        // frozen（以及 FR-07 的 verified）走实体初始值 + getter 兜底；
        // 带 default 的话 MySQL 的 bit 列建不出来——项目已经出过两次这类事故
        for (Class<?> dialect : new Class<?>[] {MySQLDialect.class, PostgreSQLDialect.class}) {
            String ddl = exportDdl(dialect);
            String line = columnDef(ddl, "frozen");
            assertTrue(line.contains("frozen"), dialect.getSimpleName() + " 上应有 frozen 列");
            assertFalse(line.contains("default"),
                    dialect.getSimpleName() + " 上 frozen 不该有 default 子句：" + line);
        }
    }

    @Test
    void bothTablesAndTheirJoinKeyExist() {
        String ddl = exportDdl(PostgreSQLDialect.class);
        assertTrue(ddl.contains("decision_datasets"));
        assertTrue(ddl.contains("decision_dataset_items"));
        assertTrue(columnDef(ddl, "dataset_id").contains("dataset_id"), "样本靠 dataset_id 挂在集上");
    }
}
