package com.devmind.decisionlab;

import com.devmind.decisionlab.checkpoint.model.DecisionCheckpointEntity;
import com.devmind.decisionlab.dataset.model.DecisionDatasetEntity;
import com.devmind.decisionlab.dataset.model.DecisionDatasetItemEntity;
import com.devmind.decisionlab.eval.model.DecisionEvaluationEntity;
import com.devmind.decisionlab.finetune.model.DecisionFinetuneEntity;
import org.hibernate.boot.Metadata;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.dialect.H2Dialect;
import org.hibernate.dialect.MySQLDialect;
import org.hibernate.dialect.PostgreSQLDialect;
import org.hibernate.tool.schema.internal.SchemaCreatorImpl;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * CAP-56 建表口径的跨库回归网（照 {@code devmind-common} 的 {@code LobColumnTypeTest} 的先例，
 * 只用 Hibernate 元数据导出 DDL，不起 Spring 上下文）。
 *
 * <p>为什么这几条必须钉住——它们全都是<b>只在某个库上才炸</b>的错误，本地 H2 跑得欢不代表线上能起：
 * <ul>
 *   <li>裸 {@code @Lob}：PG 落成 oid 大对象（auto-commit 读直接抛错），MySQL 落成 tinytext；</li>
 *   <li>{@code version} / {@code slot} 当列名：H2 保留字，建表就失败（本模块用 {@code dataset_version}、
 *       {@code serve_slot}）；</li>
 *   <li>Boolean 列带 {@code @ColumnDefault}：MySQL 的 bit 列建不出来（项目已两次事故）。</li>
 * </ul>
 * 三个方言各导一遍：H2 是本地与 E2E 的库，PG 是 140.156/143/224 的库，MySQL 是历史共享库。</p>
 */
class DecisionLabSchemaTest {

    /** FR-02 评测集的 JSON 列 */
    private static final String[] DATASET_LOB_COLUMNS =
            {"state_json", "questions_json", "gold_json", "freeze_manifest"};

    /** FR-06 产物登记的 JSON 列（指标 / 温度校准 / serve 自检报告） */
    private static final String[] CHECKPOINT_LOB_COLUMNS =
            {"metrics_json", "calibration_json", "serve_check_json"};

    /** FR-03 评测运行的证据列（命令行 / 报告 / 日志都是长文本） */
    private static final String[] EVAL_LOB_COLUMNS =
            {"command_text", "headline_json", "report_json", "logs_text"};

    /** FR-05 微调任务的证据列（切分明细 / 命令行 / 报告 / 指纹 / 日志） */
    private static final String[] FINETUNE_LOB_COLUMNS =
            {"val_item_ids_json", "command_text", "headline_json", "metrics_json",
                    "fingerprint_json", "logs_text"};

    private String exportDdl(Class<?> dialect) {
        var registry = new StandardServiceRegistryBuilder()
                .applySetting("hibernate.dialect", dialect.getName())
                .build();
        Metadata metadata = new MetadataSources(registry)
                .addAnnotatedClass(DecisionDatasetEntity.class)
                .addAnnotatedClass(DecisionDatasetItemEntity.class)
                .addAnnotatedClass(DecisionCheckpointEntity.class)
                .addAnnotatedClass(DecisionEvaluationEntity.class)
                .addAnnotatedClass(DecisionFinetuneEntity.class)
                .buildMetadata();
        String ddl = String.join("\n", new SchemaCreatorImpl(registry)
                .generateCreationCommands(metadata, false)).toLowerCase();
        StandardServiceRegistryBuilder.destroy(registry);
        return ddl;
    }

    /**
     * 取该列的 DDL 片段（从列名到下一个逗号）。
     *
     * <p>不能按行切：{@code SchemaCreatorImpl} 把整条 CREATE TABLE 输出成一行，
     * 按行取会拿到整张表——于是"id 列的 {@code generated by default as identity}"会被误判成
     * frozen 列有 default（第一版就是这么红的）。按列名到逗号切片才谈得上"看这一列"。</p>
     */
    private static String columnDef(String ddl, String column) {
        int start = ddl.indexOf(" " + column + " ");
        if (start < 0) {
            return "";
        }
        int end = ddl.indexOf(',', start);
        return end < 0 ? ddl.substring(start) : ddl.substring(start, end);
    }

    @Test
    void pgLobColumnsAreInlineTextNotOid() {
        String ddl = exportDdl(PostgreSQLDialect.class);
        for (String column : allLobColumns()) {
            assertTrue(columnDef(ddl, column).contains(" text"),
                    "PG 上 " + column + " 应为 text（@Lob 必须配 @JdbcTypeCode(LONGVARCHAR)）");
        }
        assertFalse(ddl.contains(" oid "), "PG 不应出现 oid 大对象列——那会让读写炸在 auto-commit 上");
    }

    @Test
    void mysqlLobColumnsAreLongtext() {
        String ddl = exportDdl(MySQLDialect.class);
        for (String column : allLobColumns()) {
            assertTrue(columnDef(ddl, column).contains("longtext"),
                    "MySQL 上 " + column + " 应为 longtext（依赖 @Column(length = 16_777_216)）");
        }
    }

    @Test
    void versionAndSlotColumnsAreRenamedSoH2CanCreateTheTables() {
        for (Class<?> dialect : new Class<?>[] {H2Dialect.class, PostgreSQLDialect.class, MySQLDialect.class}) {
            String ddl = exportDdl(dialect);
            assertTrue(columnDef(ddl, "dataset_version").contains("dataset_version"),
                    dialect.getSimpleName() + " 上评测集版本列应为 dataset_version（version 是 H2 保留字）");
            assertFalse(ddl.contains(" version "),
                    dialect.getSimpleName() + " 上不该有裸 version 列——建表会直接失败");
            assertTrue(columnDef(ddl, "serve_slot").contains("serve_slot"),
                    dialect.getSimpleName() + " 上服务槽位列应为 serve_slot");
            assertFalse(ddl.contains(" slot "),
                    dialect.getSimpleName() + " 上不该有裸 slot 列");
        }
    }

    @Test
    void booleanColumnsCarryNoDefaultClause() {
        // frozen 与 verified 都走实体初始值 + getter 兜底（存量行由 DecisionLabMigration 补）；
        // 带 default 的话 MySQL 的 bit 列建不出来——项目已经出过两次这类事故
        for (Class<?> dialect : new Class<?>[] {MySQLDialect.class, PostgreSQLDialect.class}) {
            String ddl = exportDdl(dialect);
            for (String column : new String[] {"frozen", "verified"}) {
                String def = columnDef(ddl, column);
                assertTrue(def.contains(column), dialect.getSimpleName() + " 上应有 " + column + " 列");
                assertFalse(def.contains("default"),
                        dialect.getSimpleName() + " 上 " + column + " 不该有 default 子句：" + def);
            }
        }
    }

    @Test
    void allFiveTablesAndTheirJoinKeysExist() {
        String ddl = exportDdl(PostgreSQLDialect.class);
        assertTrue(ddl.contains("decision_datasets"));
        assertTrue(ddl.contains("decision_dataset_items"));
        assertTrue(ddl.contains("decision_checkpoints"));
        assertTrue(ddl.contains("decision_evaluations"));
        assertTrue(ddl.contains("decision_finetunes"));
        assertTrue(columnDef(ddl, "dataset_id").contains("dataset_id"), "样本靠 dataset_id 挂在集上");
        // 列表页要显示"上次自检过了没有"，靠这一列免得逐行解析自检报告 JSON
        assertTrue(columnDef(ddl, "serve_check_status").contains("serve_check_status"));
        // 放行史三个字段（谁/何时/凭什么）在撤销后要留着，不能靠 verified 一个布尔承载
        for (String column : new String[] {"verified_by", "verified_at", "verified_note"}) {
            assertTrue(columnDef(ddl, column).contains(column), "产物表应有 " + column);
        }
    }

    /**
     * 评测行要能独立说清"这次是在什么上跑的、跑成什么样"——即便数据集被修订、产物登记被删掉。
     * 所以名/版本/路径这些是<b>快照列</b>，不是外键 join 出来的。
     */
    @Test
    void evaluationRowCarriesItsOwnSnapshotAndOutcome() {
        String ddl = exportDdl(PostgreSQLDialect.class);
        for (String column : new String[] {"dataset_name", "dataset_version", "question_set_version",
                "checkpoint_name", "checkpoint_path", "base_checkpoint_path", "node_id",
                "timeout_seconds", "report_status", "exit_code", "error_summary",
                "started_at", "finished_at", "created_by"}) {
            assertTrue(columnDef(ddl, column).contains(column), "评测表应有 " + column);
        }
    }

    /**
     * 微调行要独立说得清"这次是怎么切的、在哪训的、训出什么"——训练集会被修订、产物登记可能被删、
     * 基座来源可能被改。所以切分（{@code val_item_ids_json} + 两个条数 + 判据）、回评集、基座路径、
     * 产出目录、超参、以及收尾的三样（指纹 / 产物 id / 回评 id + 失败原因）都是自己的列。
     */
    @Test
    void finetuneRowCarriesItsSplitHyperparamsAndOutcome() {
        String table = tableDef(exportDdl(PostgreSQLDialect.class), "decision_finetunes");
        for (String column : new String[] {"eval_dataset_id", "eval_dataset_version",
                "train_count", "val_count", "split_seed", "train_ratio", "val_item_ids_json",
                "base_checkpoint_path", "base_serve_slot", "output_path", "python_path",
                "epochs", "learning_rate", "batch_size", "train_seed", "launcher",
                "fingerprint_json", "checkpoint_id", "eval_id", "post_error",
                "report_status", "started_at", "finished_at"}) {
            assertTrue(columnDef(table, column).contains(column), "微调表应有 " + column);
        }
        // 基座与产出各占一列：合成一列的话，"这份产物是从谁训出来的"与"这次训出了哪份产物"
        // 就成了同一个字段的两个意思（一个是输入，一个是输出）
        assertTrue(columnDef(table, "base_checkpoint_id").contains("base_checkpoint_id"),
                "微调表要有基座 id");
        assertTrue(columnDef(table, "checkpoint_id").contains("checkpoint_id"),
                "微调表要有产出的产物 id（与基座是两个列）");
    }

    private static String[] concat(String[] a, String[] b) {
        String[] out = new String[a.length + b.length];
        System.arraycopy(a, 0, out, 0, a.length);
        System.arraycopy(b, 0, out, a.length, b.length);
        return out;
    }

    /**
     * 取某张表的 DDL 片段（从它的 {@code create table} 到下一张表开始）。
     *
     * <p>{@link #columnDef} 在整个 DDL 里找列名，同名不同表的列（{@code checkpoint_id} 在评测表与
     * 微调表都有）会取到<b>先出现的那张表</b>——问"这一列在不在微调表里"就不准了。要精确问一张表的
     * 列，得先把那张表切出来。</p>
     */
    private static String tableDef(String ddl, String table) {
        int start = ddl.indexOf("create table " + table + " ");
        if (start < 0) {
            return "";
        }
        int next = ddl.indexOf("create table ", start + 1);
        return next < 0 ? ddl.substring(start) : ddl.substring(start, next);
    }

    /** 五张表的全部 JSON 长文本列（新表加列时只改这一处，两个方言的回归网自动跟上） */
    private static String[] allLobColumns() {
        return concat(concat(concat(DATASET_LOB_COLUMNS, CHECKPOINT_LOB_COLUMNS),
                EVAL_LOB_COLUMNS), FINETUNE_LOB_COLUMNS);
    }
}
